### ISSUE TITLE
unresolved import `std::boxed::FnBox`

### ISSUE THREAD

**Issue by jamesdwilson** [StefanoOrdine/rust-reactjs#3]
Linux Mint 19.1
$ uname -a
Linux james-laptop 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ git rev-parse --short HEAD
65bf63f
$ rustc --version
rustc 1.40.0-nightly (2e7244807 2019-10-04)
$ cargo run
   Compiling rocket v0.4.0
error[E0432]: unresolved import `std::boxed::FnBox`
 --> /home/james/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.0/src/fairing/ad_hoc.rs:2:5
  |
2 | use std::boxed::FnBox;
  |     ^^^^^^^^^^^^^^^^^ no `FnBox` in `boxed`

error: aborting due to previous error
$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/james/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

installed targets for active toolchain
--------------------------------------

asmjs-unknown-emscripten
wasm32-unknown-emscripten
wasm32-unknown-unknown
x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.40.0-nightly (2e7244807 2019-10-04)

===
Possibly related:
https://stackoverflow.com/questions/57943669/why-rust-fnbox-example-error-no-fnbox-in-boxed

**Comment by bachrc** [comment]
Identified the issue. I'm on it.
